apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: piknf9f5f-go 
  janus-idp.io/tekton: piknf9f5f-go
  backstage.io/kubernetes-id: piknf9f5f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: piknf9f5f-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml