apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: piknf9f5f-go-gitops
  description: This is GitOps manifest for piknf9f5f-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=piknf9f5f-go
    backstage.io/kubernetes-id: piknf9f5f-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: piknf9f5f-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:piknf9f5f-go
